# Generated by Django 4.0.3 on 2022-05-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_slider_options_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='online_image',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='category',
            name='online_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='C:\\Users\\Isheanesu Magaya\\Documents\\GitHub\\Kevin\\HardReco\\media/frame.png', max_length=200, unique=True),
        ),
    ]
