# Generated by Django 4.0.3 on 2022-05-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_category_online_image_category_online_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='C:\\Users\\Isheanesu Magaya\\Documents\\GitHub\\Kevin\\HardReco\\media/frame.png', upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
