# Generated by Django 4.0.3 on 2022-05-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_category_image_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='C:\\Users\\Isheanesu Magaya\\Documents\\GitHub\\Kevin\\HardReco\\media/frame.png', null=True, upload_to='category/'),
        ),
    ]
