# Generated by Django 3.1.14 on 2022-03-09 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='person_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sys_user',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='address',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='person_code',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='sys_user',
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_code', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(null=True)),
                ('date_of_joining', models.DateField(null=True)),
                ('address', models.TextField(null=True)),
                ('sys_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='person',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='person',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.person'),
            preserve_default=False,
        ),
    ]
