# Generated by Django 3.1.14 on 2022-03-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220309_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinestore',
            name='website',
            field=models.CharField(max_length=100),
        ),
    ]
