# Generated by Django 3.1.14 on 2022-03-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220309_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinestore',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
