# Generated by Django 3.1.14 on 2022-03-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_onlinestore_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinestore',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
