# Generated by Django 4.0.3 on 2022-05-16 09:24

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecategory',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='C:\\Users\\Isheanesu Magaya\\Documents\\GitHub\\Kevin\\HardReco\\media/frame.png', null=True, upload_to=app.models.product_directory_path),
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
