# Generated by Django 4.0.3 on 2022-05-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_category_online_image_category_online_link_and_more'),
        ('app', '0011_storecategory_image_storecategory_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='online_image_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
