# Generated by Django 4.0.3 on 2022-05-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_avatar_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileIntrests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrest', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
